### ISSUE TITLE
alignment of know more button

### ISSUE THREAD

**Issue by Amankumar29** [Catalyst-IN/Catalyst-IN#100]
Make the "know more" button aligned at equal level for all
we can give gaps where there is less context and make it aligned equal to the last one.
![Screenshot (29)](https://user-images.githubusercontent.com/54955755/84774712-de553680-affb-11ea-91f1-e8f86bb82726.png)

**Comment by vinayaksh42** [comment]
Or we can hide the description of the projects and only reveal them when the user hits see more under the respective project. That way it can be aligned and look equal. Directly making the equal by using space won't look great.
What's your opinion? 
@Amankumar29 
@anubhavsingh16 
@codetheorem
