### ISSUE TITLE
adding buttons for better usability.

### ISSUE THREAD

**Issue by Amankumar29** [Catalyst-IN/Catalyst-IN#55]
# we can add arrow buttons on the both side of contributors section.
# screenshot
![Screenshot (18)](https://user-images.githubusercontent.com/54955755/83379707-d0979280-a3f9-11ea-89e5-db7114fa6bea.png)
your views @anubhavsingh16 ?

**Comment by anubhavsingh16** [comment]
I think a hidden arrow is nice to have when user drag cursor on
contributors then arrow visible.

**Comment by Amankumar29** [comment]
or we can have a light arrow means not that much visible.

**Comment by anubhavsingh16** [comment]
Hmm

**Comment by vinayaksh42** [comment]
@anubhavsingh16 are they really needed? it looks clean as of now. it is a bit different from the normal carousel component

**Comment by anubhavsingh16** [comment]
I think @vinayaksh42 a hidden arrow is nice to have when user drag cursor on
contributors then arrow visible. I think we can try for this

**Comment by anubhavsingh16** [comment]
A floating hidden arrow in my mind, What you think @vinayaksh42

**Comment by vinayaksh42** [comment]
sir we have used a vue.js external component and it is not possible make direct changes in it. @anubhavsingh16

**Comment by anubhavsingh16** [comment]
ok @vinayaksh42
