### ISSUE TITLE
refactor: Alignment of the footer section.

### ISSUE THREAD

**Issue by aashimgarg** [Catalyst-IN/Catalyst-IN#72]
**Description of the enhancement**
the footer Privacy Policy section can be more right aligned. it looks a little bit squashed up to the logo.
@anubhavsingh16 what are your thoughts.

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

**Comment by codetheorem** [comment]
@aashimgarg can you elaborate it more.

**Comment by Amankumar29** [comment]
#80

**Comment by anubhavsingh16** [comment]
I think we have so many important issues in this repo can we work together for 1 week to solve all of them. Every mentor, Admin, members and contributors can we?
