### ISSUE TITLE
Some links on the website are broken

### ISSUE THREAD

**Issue by pushpinderpalsingh** [Catalyst-IN/Catalyst-IN#76]
Some links for section like Tasks of Happiness are broken. Fix it this and any other link you find broken.

**Comment by JyotiJauhari** [comment]
Should I remove the link from those images?

**Comment by vinayaksh42** [comment]
@JyotiJauhari are you going to do this issue?

**Comment by JyotiJauhari** [comment]
@vinayaksh42 
No .
